name: test_app
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  dartz: ^0.10.1
  internet_connection_checker_plus: ^2.3.0
  flutter_easyloading: ^3.0.5
  image_picker: ^1.0.7
  get_it: ^7.6.7
  injectable: ^2.3.2
  flutter_bloc: ^8.1.4
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  flutter_cache_manager: ^3.3.1
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  easy_localization: ^3.0.5
  cached_network_image: ^3.3.1
  dropdown_search: ^5.0.6
  country_picker: ^2.0.25
  shimmer: ^3.0.0
  flutter_dotenv: ^5.1.0
  animated_custom_dropdown: ^3.1.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/.env

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg